-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgVFqPqTJHHfnJuSIfXffR4FYwK6kWufZfAqSWaVmKLdygCgYIKoZIzj0DAQehRANCAAQMtJR0Q54NGMO2LJ8KMo3RYGK+VkzWR/fk/+DKfiN0ilxfRgUrN2mdNakMs/g2hxJ75zBlsYTa7NaLxggdigLS
-----END PRIVATE KEY-----